added etherscan station
mysteriumnetwork/payments pull request #133
Opened 2021-09-10 10:34 UTC by Guillembonet

Added etherscan API to gas stations for ethereum mainnet

Signed-off-by: Guillem <guillem@mysterium.network>

2021-09-10 12:28 UTC, tomasmik requested changes

2021-09-10 12:28 UTC, tomasmik commented on transfer/gas/etherscan.go
> +		return nil, errors.New("etherscan API request failed")
also provide what happened, status code/message or something. WIthout that the error is a black box.

2021-09-10 12:28 UTC, tomasmik commented on transfer/gas/etherscan.go
> +	fmt.Println(string(resp))
leftover

2021-09-10 12:28 UTC, tomasmik commented on transfer/gas/etherscan.go
> +	APIKey      string
probably no need to keep these public

2021-09-13 07:39 UTC, vkuznecovas reviewed
What he said.

2021-09-13 08:45 UTC, Guillembonet commented
Will do another PR together with refactor with this fixed

2021-09-13 08:45 UTC, closed without merging