clean up old entries (configurable)
mysteriumnetwork/payments pull request #223
Opened 2022-07-06 13:39 UTC by Guillembonet

Possibility to clean up old entries #222 

Signed-off-by: Guillem Bonet <guillem@mysterium.network>

2022-07-06 13:46 UTC, n10ty approved these changes

2022-07-06 13:47 UTC, n10ty commented
Nice

2022-07-06 16:27 UTC, tomasmik requested changes

2022-07-06 16:27 UTC, tomasmik commented on transaction/depot.go
> +	GetDeliveredDeliveryRequests(chainID int64, sender common.Address, olderThan time.Time, limit uint64) ([]Delivery, error)
Could we make this a separate interface and also optional? My reasoning here is quite simple, maybe I don't want to cleanup any entries, why would I bother implementing this part of the interface or mocking up the methods. The cleaner for me seems more or less like an optional part of the depot and the interface is already pretty large.

2022-07-06 16:27 UTC, tomasmik commented on transaction/depot.go
> +			go d.cleanupOldEntries(s)
Do you really need a separate cleaner goroutine for each worker? I think it's really enough to just clean up after X in a single routine. Simply filter by timestamp.

2022-07-07 10:20 UTC, tomasmik approved these changes

2022-07-07 10:23 UTC, merged